//
//  Rule.m
//  Practice
//
//  Created by Ibrahim on 20/05/2016.
//  Copyright © 2016 Ibrahim. All rights reserved.
//


// IMPORT

#import "Dimension.h"


// GENERAL




// GENERAL

    /* SPACE */

    int const GENERAL_SPACE_MEDIUM = 20;
    int const GENERAL_SPACE_TINY = GENERAL_SPACE_MEDIUM / 4;
    int const GENERAL_SPACE_LITTLE = GENERAL_SPACE_MEDIUM / 2;
    int const GENERAL_SPACE_SMALL = GENERAL_SPACE_MEDIUM * 0.75;
    int const GENERAL_SPACE_LARGE = GENERAL_SPACE_MEDIUM * 1.5;
    int const GENERAL_SPACE_HUGE = GENERAL_SPACE_MEDIUM * 2;
    int const GENERAL_SPACE_ENORMOUS = GENERAL_SPACE_MEDIUM * 3;

    /* MEASUREMENT */

    int const GENERAL_WIDTH_MEDIUM = 220;
    int const GENERAL_WIDTH_SHORT = GENERAL_WIDTH_MEDIUM / 2;
    int const GENERAL_WIDTH_LONG = GENERAL_WIDTH_MEDIUM * 4;

    int const GENERAL_HEIGHT_SINGLE = 36;
    int const GENERAL_HEIGHT_DOUBLE = GENERAL_HEIGHT_SINGLE * 2;
    int const GENERAL_HEIGHT_TRIPPLE = GENERAL_HEIGHT_SINGLE * 3;

    int const GENERAL_WIDTH_THIN = 1;
    int const GENERAL_WIDTH_REGULAR = 2;
    int const GENERAL_WIDTH_THICK = 4;

    int const GENERAL_RADIUS_FORM = 8;


// OBJECT / SHAPE

    /* ICON */

    int const ICON_SIZE_MEDIUM = 48;
    int const ICON_SIZE_TINY = ICON_SIZE_MEDIUM / 2;
    int const ICON_SIZE_SMALL = ICON_SIZE_MEDIUM * 0.75;
    int const ICON_SIZE_LARGE = ICON_SIZE_MEDIUM * 1.5;
    int const ICON_SIZE_XLARGE = ICON_SIZE_MEDIUM  * 2;
    int const ICON_SIZE_XXLARGE = ICON_SIZE_MEDIUM * 3;
    int const ICON_SIZE_XXXLARGE = ICON_SIZE_MEDIUM * 4;

    /* ARC */

    int const ARC_SIZE_FULLSCREEN = 290;
    int const ARC_SIZE_HOME = 240;
    int const ARC_SIZE_HEADER = 150;

    /* LOGO */

    int const LOGO_WIDTH_HAT = 120;
    int const LOGO_HEIGHT_HAT = 105;
    int const LOGO_WIDTH_HORIZONTAL = 170;
    int const LOGO_HEIGHT_HORIZONTAL = 50;

    /* DESCRIPTOR */

    int const DESCRIPTOR_WIDTH_VIEW = 130;
    int const DESCRIPTOR_HEIGHT_VIEW = 70;


// INPUT

    /* BORDER */

    int const INPUT_WIDTH_BORDER = GENERAL_WIDTH_THIN;
    int const INPUT_RADIUS_BORDER = GENERAL_RADIUS_FORM;

    /* BACKGROUND */

    CGFloat const INPUT_OPACITY_BACKGROUND = 0.6;

    /* PROGRESS VIEW */

    int const PROGRESSVIEW_HEIGHT_BAR = 8;


    // NAVIGATION

    int const NAVIGATION_WIDTH_CONTAINER = 310;
    int const NAVIGATION_HEIGHT_CONTAINER = 1024;
    int const NAVIGATION_HEIGHT_GRIP = ICON_SIZE_SMALL / 2;// ICON_SIZE_MEDIUM / 4;

    /* PROFILE */

    int const PROFILE_WIDTH_VIEW = 256;
    int const PROFILE_HEIGHT_VIEW = GENERAL_HEIGHT_SINGLE * 4;

    /* HEADER */

    int const NAVIGATION_HEIGHT_HEADER = 70;
    int const NAVIGATION_WIDTH_HEADER = 192;


    /* DETAIL */

    int const NAVIGATION_HEIGHT_DETAIL = 56;
    int const NAVIGATION_WIDTH_DETAIL = 152;


// SLIDER

    /* CONTROLLER */

    int const SLIDER_HEIGHT_CONTROLLER = GENERAL_HEIGHT_SINGLE;
    int const BUTTON_SIZE_SLIDER = ICON_SIZE_MEDIUM / 4;

    /* SLIDER */

    int const SLIDER_HEIGHT_SCROLLVIEW = 568;


// BUTTON

int const BUTTON_RADIUS_BORDER = GENERAL_RADIUS_FORM;
int const BUTTON_SIZE_SMALL = ICON_SIZE_SMALL;
int const BUTTON_SIZE_MEDIUM = ICON_SIZE_MEDIUM;
int const BUTTON_HEIGHT_ALERT = 45;


// GUIDE

    /* HEADER */

    int const GUIDEHEADER_WIDTH_VIEW = 290;
    int const GUIDEHEADER_HEIGHT_VIEW = ICON_SIZE_LARGE;

    /* DETAIL */

    int const GUIDEDETAIL_SIZE_BUTTON = ICON_SIZE_SMALL;
    int const GUIDEDETAIL_WIDTH_VIEW = GUIDEDETAIL_SIZE_BUTTON * 2;


// INFORMATION

int const INFORMATION_HEIGHT_VIEW = 100;


// FORM

int const FORM_SIZE_LABELNUMBER = ICON_SIZE_SMALL;


// MODULE

int const MODULE_HEIGHT_VIEW = ICON_SIZE_LARGE * 1.5;
