//
//  Theme.m
//  Practice
//
//  Created by Ibrahim on 20/05/2016.
//  Copyright © 2016 Ibrahim. All rights reserved.
//


// IMPORT

#import "Font Size.h"


// GENERAL

CGFloat const FONTSIZE_GENERAL_MEDIUM = 18;
CGFloat const FONTSIZE_GENERAL_TINY = 10;
CGFloat const FONTSIZE_GENERAL_LITTLE = 12;
CGFloat const FONTSIZE_GENERAL_SMALL = 14;
CGFloat const FONTSIZE_GENERAL_LARGE = 21;
CGFloat const FONTSIZE_GENERAL_HUGE = 28;
CGFloat const FONTSIZE_GENERAL_ENORMOUS = 36;


// FORM

CGFloat const FONTSIZE_FORM_SECTION = FONTSIZE_GENERAL_LARGE;
CGFloat const FONTSIZE_FORM_PARAGRAPH = FONTSIZE_GENERAL_SMALL;
CGFloat const FONTSIZE_FORM_NOTE = FONTSIZE_GENERAL_SMALL;
CGFloat const FONTSIZE_FORM_NUMBER = FONTSIZE_GENERAL_MEDIUM;
CGFloat const FONTSIZE_FORM_QUESTION = FONTSIZE_GENERAL_MEDIUM;

// PHOTO

CGFloat const FONTSIZE_PHOTO_SECTION = FONTSIZE_GENERAL_HUGE;
CGFloat const FONTSIZE_PHOTO_HEADER = FONTSIZE_GENERAL_ENORMOUS - 4;
CGFloat const FONTSIZE_PHOTO_DETAIL = FONTSIZE_GENERAL_MEDIUM;


// DECORATOR

    /* DESCRIPTOR */

    CGFloat const FONTSIZE_DESCRIPTOR_HEADER = FONTSIZE_GENERAL_TINY + 1;
    CGFloat const FONTSIZE_DESCRIPTOR_WEBSITE = FONTSIZE_GENERAL_TINY;
    CGFloat const FONTSIZE_DESCRIPTOR_DETAIL = FONTSIZE_GENERAL_TINY - 2;


// INPUT

CGFloat const FONTSIZE_TEXTFIELD_FORM = FONTSIZE_GENERAL_MEDIUM;
CGFloat const FONTSIZE_SEGMENTEDCONTROL_FORM = FONTSIZE_GENERAL_MEDIUM;


// NAVIGATION

    /* PROFILE */

    CGFloat const FONTSIZE_PROFILE_HEADER = FONTSIZE_GENERAL_LARGE + 3;
    CGFloat const FONTSIZE_PROFILE_DETAIL = FONTSIZE_GENERAL_MEDIUM;

    /* HEADER */

    CGFloat const FONTSIZE_NAVIGATION_HEADER = FONTSIZE_GENERAL_MEDIUM;

    /* DETAIL */

    CGFloat const FONTSIZE_NAVIGATION_DETAIL = FONTSIZE_GENERAL_SMALL;


// BUTTON

CGFloat const FONTSIZE_BUTTON_FORM = FONTSIZE_GENERAL_MEDIUM;
CGFloat const FONTSIZE_BUTTON_PHOTO = FONTSIZE_GENERAL_SMALL;


// GUIDE

    /* HEADER */

    CGFloat const FONTSIZE_GUIDEHEADER_TITLE = FONTSIZE_GENERAL_MEDIUM;
    CGFloat const FONTSIZE_GUIDEHEADER_STEP = FONTSIZE_GENERAL_ENORMOUS;
    CGFloat const FONTSIZE_GUIDEHEADER_STATE = FONTSIZE_GENERAL_LITTLE;

    /* DETAIL */

    CGFloat const FONTSIZE_GUIDEDETAIL_STEP = FONTSIZE_GENERAL_SMALL;


// HEADER

CGFloat const FONTSIZE_HEADER_TITLE = FONTSIZE_GENERAL_ENORMOUS - 4;


// MODULE

CGFloat const FONTSIZE_MODULE_TITLE = FONTSIZE_GENERAL_MEDIUM;
CGFloat const FONTSIZE_MODULE_HEADER = FONTSIZE_GENERAL_LITTLE;
CGFloat const FONTSIZE_MODULE_DETAIL = FONTSIZE_GENERAL_SMALL;
CGFloat const FONTSIZE_MODULE_PROGRESS = FONTSIZE_GENERAL_MEDIUM;
